name: Point main branch to that which tracks upstream after rebasing our commits onto it # Only for main panda-re repo, not forks

on:
  workflow_dispatch:
  push:

jobs:
  rebase_onto_qemu_master:
    if: github.repository  == 'panda-re/qemu'
    runs-on: panda-arc
