name: Point main branch to that which tracks upstream after rebasing our commits onto it # Only for main panda-re repo, not forks

on:
  workflow_dispatch:

jobs:
  rebase_onto_qemu_master:
    if: github.repository  == 'panda-re/qemu'
    runs-on: panda-arc
    steps:
      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Make main_previous point to main's HEAD and make main point to master's HEAD
        run: |
          # Get main's SHA
          MAIN_SHA=$(
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/panda-re/qemu/git/ref/heads/main \
            | jq .object.sha \
            | tr -d \"
          )

          # Set main_previous to point to MAIN_SHA
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/panda-re/qemu/git/refs/main_previous \
            -f "sha=${MAIN_SHA}" -F "force=true"

          # Get master's SHA
          MASTER_SHA=$(
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/panda-re/qemu/git/ref/heads/master \
            | jq .object.sha \
            | tr -d \"
          )

          # Set main to point to MASTER_SHA
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/panda-re/qemu/git/refs/main \
            -f "sha=${MASTER_SHA}" -F "force=true"