name: Build and Publish Docker Container and Pypanda Docs # Only for main panda-re repo, not forks

on:
  push:
    branches:
      - main

jobs:
  build_release_assets:
    if: github.repository  == 'panda-re/qemu' && github.ref == 'refs/heads/main'
    runs-on: panda-arc
    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install git curl jq -y
      
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          tag_prefix: panda
          release_branch: main
          use_api: true
      
      - name: 'Login to Docker Registry'
        uses: docker/login-action@v3
        with:
          username: pandare
          password: ${{secrets.pandare_dockerhub}}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0
      
      - name: Build panda:latest
        uses: docker/build-push-action@v6.13.0
        with:
          push: true
          context: ${{ github.workspace }}
          cache-from: type=registry,ref=pandare/panda-ng:build-latest
          cache-to: type=registry,ref=pandare/panda-ng:build-latest
          tags: |
            pandare/panda-ng:${{ github.sha }}
            pandare/panda-ng:${{ steps.version.outputs.prefixed-v-version }}
            pandare/panda-ng:latest
      
      - name: Build package
        working-directory: panda/debian
        run: ./setup.sh Ubuntu 22.04

      - name: Upload wheel and debian packages to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.prefixed-v-version }}
          files: |
            panda/debian/pandare*.deb
            panda/debian/libpanda-ng.tar.gz