name: Build and Publish Docker Container and Pypanda Docs # Only for main panda-re repo, not forks

on:
  push:
    branches:
      - main

jobs:
  build_release_assets:
    if: github.repository  == 'panda-re/qemu' && github.ref == 'refs/heads/main'
    runs-on: panda-arc
    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install git curl jq -y
      
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          tag_prefix: panda
          release_branch: main
          use_api: true

      - name: Trust Harbor's self-signed certificate
        run: |
          echo "Fetching certificate from registry"
          openssl s_client -showcerts -connect ${{ secrets.PANDA_ARC_REGISTRY }}:443 < /dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee /usr/local/share/ca-certificates/harbor.crt > /dev/null
          sudo update-ca-certificates
      
      - name: Install dependencies and label git workspace safe
        run: |
          sudo apt-get update
          sudo apt-get -y install git curl jq gzip tmux
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-config-inline: |
            [registry."${{ secrets.PANDA_ARC_REGISTRY }}"]
              insecure = true
              http = true
      
      - name: 'Login to Docker Registry'
        uses: docker/login-action@v3
        with:
          username: pandare
          password: ${{secrets.pandare_dockerhub}}
          
      - name: Log in to Rehosting Arc Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.PANDA_ARC_REGISTRY }}
          username: ${{ secrets.PANDA_ARC_REGISTRY_USER }}
          password: ${{ secrets.PANDA_ARC_REGISTRY_PASSWORD }}
      
      - name: Build Docker image and push to Dockerhub
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ github.workspace }}
          push: true
          cache-from: |
            type=registry,ref=${{secrets.PANDA_ARC_REGISTRY}}/pandare/qemu:cache,mode=max
          cache-to: |
            type=registry,ref=${{secrets.PANDA_ARC_REGISTRY}}/pandare/qemu:cache,mode=max
          tags: |
            pandare/qemu:${{ github.sha }}
            pandare/qemu:${{ steps.version.outputs.prefixed-v-version }}
            pandare/qemu:latest
          load: true
          build-args: |
            REGISTRY=${{ secrets.PANDA_ARC_REGISTRY }}/proxy
      
      - name: Build Docker image and load packager to local Docker
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ github.workspace }}
          push: false
          target: packager
          cache-from: |
            type=registry,ref=${{secrets.PANDA_ARC_REGISTRY}}/pandare/qemu:cache,mode=max
            type=registry,ref=${{secrets.PANDA_ARC_REGISTRY}}/pandare/qemu:package_cache,mode=max
          cache-to: |
            type=registry,ref=${{secrets.PANDA_ARC_REGISTRY}}/pandare/qemu:package_cache,mode=max
          tags: |
            packager
          build-args: |
            REGISTRY=${{ secrets.PANDA_ARC_REGISTRY }}/proxy
          load: true

      - name: Build package
        working-directory: panda/debian
        run: |
          docker run --rm -v $(pwd):/out packager bash -c "cp /pandare.deb /libpanda-ng.tar.gz /out"
          mv pandare.deb pandare-22.04.deb

      - name: Upload wheel and debian packages to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.prefixed-v-version }}
          files: |
            panda/debian/pandare*.deb
            panda/debian/libpanda-ng.tar.gz