name: Automatically rebase main branch onto qemu/qemu master branch # Only for main panda-re repo, not forks

on:
  workflow_dispatch:

jobs:
  rebase_onto_qemu_master:
    if: github.repository  == 'panda-re/qemu'
    runs-on: panda-arc
    steps:
      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      # Requires pre-existing branch "master"
      - name: Sync QEMU master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh repo sync panda-re/qemu --source qemu/qemu --branch master

      - name: Create a PR to rebase main onto master if one does not already exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$(gh pr list --base master --state open --json id --jq 'length')" == "0" ]; then  # Only create PR if one does not already exist
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/panda-re/qemu/pulls \
            -f "title=Rebase main onto QEMU master" -f "head=main" -f "base=master"
          fi

      # - name: Make main_previous point to main's HEAD

      # - name: Make main point to upstream_master's HEAD
