name: Automatically rebase main branch onto qemu/qemu master branch # Only for main panda-re repo, not forks

on:
  workflow_dispatch:

jobs:
  rebase_onto_qemu_master:
    if: github.repository  == 'panda-re/qemu'
    runs-on: panda-arc
    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install git -y
      
      # We can't delete PRs on github, so try the rebase locally first
      # OR open the rebase PR regardless and then have someone fix it.
      - name: Check out local main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # - name: Configure committer name and email
      #   run: |
      #     git config user.name "Test rebase"
      #     git config user.email "connorc0405@gmail.com"

      - name: Check out upstream qemu master branch and push to our repo
        run: |
          # git remote add upstream https://github.com/qemu/qemu
          # git fetch upstream master
          git fetch https://github.com/qemu/qemu master:upstream_master
          git checkout upstream_master
          git remote -v # test
          git push --set-upstream origin upstream_master

      # - name: Rebase local main onto upstream qemu master
      #   # run: git rebase upstream/master
      #   run: git rebase upstream_master

      - name: Create a PR to rebase main onto upstream_master
        run: |
          git checkout main
          git remote -v # testing
          apt update
          gh pr create --dry-run --base upstream_master

      # - name: Make main_previous point to main's HEAD

      # - name: Make main point to upstream_master's HEAD
