name: Automatically rebase main branch onto qemu/qemu master branch # Only for main panda-re repo, not forks

on:
  workflow_dispatch:

jobs:
  rebase_onto_qemu_master:
    if: github.repository  == 'panda-re/qemu'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Requires pre-existing branch "master"
      - name: Sync QEMU master branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh repo sync panda-re/qemu --source qemu/qemu --branch master

      - name: Create a PR to rebase main onto master if one does not already exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$(gh pr list --repo panda-re/qemu --base master --state open --json id --jq 'length')" == "0" ]; then  # Only create PR if one does not already exist
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/panda-re/qemu/pulls \
              -f "title=Rebase main onto QEMU master" -f "head=main" -f "base=master"
          fi
