name: Automatically rebase main branch onto qemu/qemu master branch # Only for main panda-re repo, not forks

on:
  workflow_dispatch:

jobs:
  rebase_onto_qemu_master:
    if: github.repository  == 'panda-re/qemu'
    runs-on: panda-arc
    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install git -y

      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      # # We can't delete PRs on github, so try the rebase locally first
      # # OR open the rebase PR regardless and then have someone fix it.
      # - name: Check out local main branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main
      #     fetch-depth: 0

      # - name: Configure committer name and email
      #   run: |
      #     git config user.name "Test rebase"
      #     git config user.email "connorc0405@gmail.com"

      # - name: Check out upstream qemu master branch and push to our repo
      #   run: |
      #     # git remote add upstream https://github.com/qemu/qemu
      #     # git fetch upstream master
      #     git fetch https://github.com/qemu/qemu master:upstream_master
      #     git checkout upstream_master
      #     git remote -v # test
      #     git push --set-upstream origin upstream_master

      # Requires pre-existing branch "master"
      - name: Sync QEMU master branch
        run: gh repo sync panda-re/qemu --source qemu/qemu --branch master

      # - name: Rebase local main onto upstream qemu master
      #   # run: git rebase upstream/master
      #   run: git rebase upstream_master

      # - name: Create a PR to rebase main onto master
      #   run: |
      #     git checkout main
      #     git remote -v # testing
      #     apt update
      #     gh pr create --dry-run --base master

      # - name: Create a PR to rebase main onto master
      #   run: |
      #     gh api \
      #     --method POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     /repos/panda-re/qemu/pulls \
      #     -f "title=Rebase main onto QEMU master" -f "head=main" -f "base=master"

      # - name: Make main_previous point to main's HEAD

      # - name: Make main point to upstream_master's HEAD
